---
  - name: Change hostname
    hostname: name={{ hostname_name }}

  - name: Copy hosts
    template: src=hosts.j2 dest=/etc/hosts

  - name: Update package cache
    apt: update_cache=yes

  - name: Upgrade OS
    apt: upgrade=yes

  - name: System restart after upgrade os
    command: shutdown -r now
    async: 0
    poll: 0
    ignore_errors: true

  - name: Wait for the server to go down after reboot
    local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=stopped
    sudo: false

  - name: Waiting for server to come back online
    local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay=10
    sudo: false

  - name: Add locales
    shell: bash -c "echo \"export LANGUAGE=en_US.UTF-8\" >> ~/.bashrc"
    shell: bash -c "echo \"export LANG=en_US.UTF-8\" >> ~/.bashrc"
    shell: bash -c "echo \"export LC_ALL=en_US.UTF-8\" >> ~/.bashrc"


  - name: Generate locales
    shell: locale-gen en_US.UTF-8

  - name: Reconfigure locales
    shell: dpkg-reconfigure locales

  - name: Install packages
    apt: pkg={{ item }} state=installed
    with_items:
      - htop
      - screen
      - curl
      - s3cmd
      - unzip
      - build-essential
      - python-pip
      - python-setuptools
      - python-dev
      - python-pycurl
      - python-lxml
      - python-virtualenv
      - virtualenvwrapper
      - libpcre3
      - libpcre3-dev